apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-troubleshoot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-troubleshoot
    app.kubernetes.io/part-of: nodejs-troubleshoot
  name: nodejs-troubleshootmpo7
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-troubleshoot
    weight: 100
status: {}
