apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-troubleshoot
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jmayorgarh-tenant/nodejs-troubleshoot/nodejs-troubleshoot@sha256:47efe9ae57b8ffabc71b2fa3e3f63b01df701a311d4010c04f92220cde222655
        name: container-image
        resources: {}
status: {}
